apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: gct.it18.dharani@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:

      name: letsencrypt-account-private-key

    solvers:
    - http01:
        ingress:
          class: nginx
